### ISSUE TITLE
Usage guide

### ISSUE THREAD

**Issue by Ascendzor** [ethereumjs/ethashjs#15]
Hi Ethereum Javascripters,

I'm a web developer who's interested in ethereum in javascript and am very interested in mining with javascript (I know it'll be slower).
While I've read Dagger-hashimoto and a lot of blockchain material, I'm confused with how to use ethashjs.

I see that it says it can be browserified but I have no idea how to actually use it.

I have geth running with jsonrpc enabled and working with curl requests. But I can't figure out what I need from geth in order to run ethashjs.

Perhaps someone here could help me, what should I be doing to try and mine in the browser using ethashjs?

**Comment by RationalCoding** [comment]
I've been attempting to do the same thing, and this is what I've come up with so far (which may be completely wrong). I'm following [this guide](https://github.com/ethereum/wiki/wiki/Ethash).

```javascript
 function mine (fullSize, header, difficulty, blockNumber) {

  var target = Math.floor(2**256 / difficulty) // Not sure on the target calculation here
  var nonce = randomInt(10, 100)
  
  self._ethash.loadEpoc(blockNumber, function () { // loadEpoc is undocumented, so this could be the wrong way to create the cache 
    while (self._ethash.run(header, nonce, fullSize).hash > target) {  // not sure how to properly compare here
      nonce = (nonce + 1) % 2**64
    }
    return nonce
  })
```

As for getting the actual inputs to this function, in the correct formats, your guess is as good as mine. Hopefully someone more knowledgable in ETH could help here.

**Comment by axic** [comment]
I think it is very unlikely to use this in the browser, given the need of ~2GB of working memory.

**Comment by RationalCoding** [comment]
The entire DAG does not need to be stored in the browser's memory. It could be streamed from a server.
